### ISSUE TITLE
torch.cuda.get_device_name -> Cannot re-initialize CUDA in forked subprocess

### ISSUE THREAD

**Issue by avito-ds** [avito-tech/aqueduct#11]
Hi!

The call of torch.cuda.get_device_name() results in an error
```
[2021-10-28 11:27:22,347] INFO [Flow] [pid:3602] Flow is starting
[2021-10-28 11:27:22,350] INFO [Flow] [pid:3602] Created step <__main__.SimpleHandler object at 0x7fec940ef280>, queue_in: <multiprocessing.queues.Queue object at 0x7fec940ef340>, queue_out:<multiprocessing.queues.Queue object at 0x7fec8c0d3eb0>
[2021-10-28 11:27:22,351] INFO [Flow] [pid:3606] [Worker] initialising handler SimpleHandler
[2021-10-28 11:27:22,351] INFO [Flow] [pid:3602] Flow was started
[2021-10-28 11:27:22,353] ERROR [Flow] [pid:3606] Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/aqueduct/multiprocessing.py", line 61, in _wrap
    fn(i, *args)
  File "/usr/local/lib/python3.8/site-packages/aqueduct/worker.py", line 120, in loop
    self._start()
  File "/usr/local/lib/python3.8/site-packages/aqueduct/worker.py", line 75, in _start
    self.task_handler.on_start()
  File "example.py", line 15, in on_start
    torch.zeros((10, 10), device=torch.device('cuda:0'))
  File "/usr/local/lib/python3.8/site-packages/torch/cuda/__init__.py", line 147, in _lazy_init
    raise RuntimeError(
RuntimeError: Cannot re-initialize CUDA in forked subprocess. To use CUDA with multiprocessing, you must use the 'spawn' start method
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/aqueduct/multiprocessing.py", line 61, in _wrap
    fn(i, *args)
  File "/usr/local/lib/python3.8/site-packages/aqueduct/worker.py", line 120, in loop
    self._start()
  File "/usr/local/lib/python3.8/site-packages/aqueduct/worker.py", line 75, in _start
    self.task_handler.on_start()
  File "example.py", line 15, in on_start
    torch.zeros((10, 10), device=torch.device('cuda:0'))
  File "/usr/local/lib/python3.8/site-packages/torch/cuda/__init__.py", line 147, in _lazy_init
    raise RuntimeError(
RuntimeError: Cannot re-initialize CUDA in forked subprocess. To use CUDA with multiprocessing, you must use the 'spawn' start method
[2021-10-28 11:27:23,353] ERROR [Flow] [pid:3602] The process 3606 for SimpleHandler handler is dead
[2021-10-28 11:27:23,353] INFO [Flow] [pid:3602] Flow is stopping
```

aqueduct-1.7.1, base example:
```
import asyncio

import torch
from aqueduct.flow import Flow, FlowStep
from aqueduct.handler import BaseTaskHandler
from aqueduct.task import BaseTask

torch.cuda.get_device_name()


class SimpleHandler(BaseTaskHandler):

    def on_start(self):
        torch.zeros((10, 10), device=torch.device('cuda:0'))

    def handle(self, *tasks: BaseTask):
        pass


def main():
    flow = Flow(FlowStep(SimpleHandler()))
    flow.start()

    coro = flow.process(BaseTask())
    asyncio.get_event_loop().run_until_complete(coro)


if __name__ == '__main__':
    main()
```

**Comment by bugrimov** [comment]
This is happens because you using torch+cuda in main process. To avoid this problem you need to use torch+cuda in child process, you can try this:
```
    def on_start(self):
        torch.cuda.get_device_name()
        torch.zeros((10, 10), device=torch.device('cuda:0'))
```
We think how to avoid this in future, but now you have this workaround.
